### ISSUE TITLE
[2pts] Data and Database setup 

### ISSUE THREAD

**Issue by cloudmytribe** [cloudmytribe/my-cloud-resume#1]
# Task **requirements**
- [ ] Define structure of your **resume** data 
- [ ] Choose relevant noSQL database
- [ ] Implement resume data to database
